apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-db-agent
  namespace: appdynamics-db
  labels:
    app: appd-db-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appd-db-agent
  template:
    metadata:
      labels:
        app: appd-db-agent
    spec:
      containers:
      - name: db-agent
        image: appdynamics/db-agent:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /db-agent/conf/controller-info.xml
          subPath: controller-info.xml
        env:
        - name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
          value: "appd-db-agent_NFR"
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: "tietoevry-prod.saas.appdynamics.com"
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: "443"
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: "tietoevry-prod"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          value: "q43d65fajbca"
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          value: "true"
      volumes:
      - name: config-volume
        configMap:
          name: appd-db-agent-config
